# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 13:46
from __future__ import unicode_literals

from django.db import migrations, models
from collections import Counter


def find_duplicates(apps, schema_editor):
    List = apps.get_model('lists', 'List')
    for list_ in List.objects.all():
        counter = Counter()
        for item in list_.item_set.all():
            counter.update([item.text])
            if counter[item.text] > 1:
                item.text = f'{item.text} ({counter[item.text] - 1})'
                item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.RunPython(find_duplicates)
    ]
