# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-03 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_todo_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='TodoList',
        ),
    ]
