# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20191103_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='todo_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lists.TodoList'),
            preserve_default=False,
        ),
    ]
