# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_auto_20191111_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=15)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
    ]
