# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-24 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0007_list_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='sharees',
            field=models.ManyToManyField(related_name='_list_sharees_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
